import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const fixtureUrl = new URL('./fixtures/adjusted-ebitda-sec-ground-truth.json', import.meta.url)
const fixture = JSON.parse(await readFile(fixtureUrl, 'utf8'))

const REQUIRED_TICKERS = ['BE', 'CRWV', 'FCEL', 'GEV', 'IREN', 'NBIS']
const REQUIRED_PROVENANCE = [
  'form',
  'accession',
  'document',
  'tableLabel',
  'rowLabel',
  'columnLabel',
  'units',
  'url',
]

function reportedRows() {
  return fixture.companies.flatMap((company) =>
    company.periods.filter((period) => period.expectedValue != null)
      .map((period) => ({ ...period, ticker: company.ticker })))
}

test('SEC ground truth is independently sourced and broad enough for regression', () => {
  assert.match(fixture.methodology, /independently manually transcribed/i)
  assert.match(fixture.methodology, /not generated by.*production/i)
  const tickers = new Set(fixture.companies.map((company) => company.ticker))
  for (const ticker of REQUIRED_TICKERS) assert.ok(tickers.has(ticker), `missing ${ticker}`)
  assert.ok(tickers.size >= 10, 'at least ten explicitly reporting issuers are required')
})

test('Bloom Energy remains a permanent exact golden fixture', () => {
  const bloom = fixture.companies.find((company) => company.ticker === 'BE')
  assert.ok(bloom)
  const expected = new Map(bloom.periods.map((period) => [period.period, period.expectedValue]))
  assert.equal(expected.get('2023A'), 81_791_000)
  assert.equal(expected.get('2024A'), 160_651_000)
  assert.equal(expected.get('2025A'), 271_591_000)
})

test('every reported datapoint has complete SEC table provenance', () => {
  for (const row of reportedRows()) {
    assert.ok(Number.isFinite(row.expectedValue), `${row.ticker} ${row.period} value`)
    assert.ok(['CALENDAR_YEAR', 'FISCAL_YEAR', 'QUARTER', 'LTM'].includes(row.periodType),
      `${row.ticker} ${row.period} period type`)
    assert.match(row.startDate, /^\d{4}-\d{2}-\d{2}$/)
    assert.match(row.endDate, /^\d{4}-\d{2}-\d{2}$/)
    for (const field of REQUIRED_PROVENANCE) {
      assert.ok(row[field], `${row.ticker} ${row.period} missing ${field}`)
    }
    assert.match(row.url, /^https:\/\/www\.sec\.gov\/Archives\/edgar\//)
    assert.notEqual(row.metricBasis, 'STANDARDIZED_EBITDA')
  }
})

test('fiscal-year fixtures are never mapped into calendar-year production columns', () => {
  for (const row of reportedRows().filter((period) => period.periodType === 'FISCAL_YEAR')) {
    assert.equal(row.productionPeriod, null, `${row.ticker} ${row.period} must not map to a CY column`)
  }
})

test('every asserted N/A has an explicit reason', () => {
  for (const company of fixture.companies) {
    for (const row of company.periods.filter((period) => period.expectedValue == null)) {
      assert.ok(row.reason, `${company.ticker} ${row.period} missing N/A reason`)
    }
  }
})

test('LTM fixtures equal exactly four compatible reported quarters', () => {
  for (const row of reportedRows().filter((period) => period.periodType === 'LTM')) {
    assert.equal(row.components?.length, 4, `${row.ticker} ${row.period} component count`)
    assert.equal(row.components.reduce((sum, component) => sum + component.expectedValue, 0), row.expectedValue,
      `${row.ticker} ${row.period} arithmetic`)
    assert.equal(new Set(row.components.map((component) => component.definitionKey)).size, 1,
      `${row.ticker} ${row.period} definition compatibility`)
    assert.equal(new Set(row.components.map((component) => component.units)).size, 1,
      `${row.ticker} ${row.period} unit compatibility`)
    for (const component of row.components) {
      for (const field of REQUIRED_PROVENANCE) {
        assert.ok(component[field], `${row.ticker} ${row.period} component missing ${field}`)
      }
    }
  }
})
