// ─────────────────────────────────────────────────────────────────────────────
//  src/data.js  —  OPTICS ECOSYSTEM DATA
//
//  THIS IS THE SINGLE FILE TO EDIT when adding real companies.
//
//  For each layer, update the `companies` array with real entries.
//  Each company object needs these fields:
//    name          — company display name
//    ticker        — stock ticker (or "Private" / "N/A")
//    marketCap     — e.g. "$4.2B"
//    revenueGrowth — e.g. "18%"
//    grossMargin   — e.g. "62%"
//    country       — e.g. "USA"
//    type          — "Public" or "Private"
//    description   — one-sentence company description
//
//  The company count shown on the Optics map updates automatically
//  from companies.length — you do NOT need to change it anywhere else.
//
//  Also update the overview block for each layer when you have real content.
// ─────────────────────────────────────────────────────────────────────────────

export const OPTICS_LAYERS = [
  // ── LAYER 1 ────────────────────────────────────────────────────────────────
  {
    name: 'Materials, Substrates & Equipment',
    color: '#f59e0b',
    glow: 'rgba(245,158,11,0.12)',
    dim: 'rgba(245,158,11,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers the foundational raw materials, engineered substrates, and capital equipment used in photonic chip fabrication.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Soitec',
        ticker: 'SOI.PA',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'France',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'AXT',
        ticker: 'AXTI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sumitomo Electric',
        ticker: '5802.T',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'IQE',
        ticker: 'IQE.L',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'UK',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Aeluma',
        ticker: 'ALMU',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Aixtron',
        ticker: 'AIXA.DE',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Germany',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Coherent',
        ticker: 'COHR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Lumentum',
        ticker: 'LITE',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Applied Optoelectronics',
        ticker: 'AAOI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Nokia',
        ticker: 'NOK',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Finland',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'IPG Photonics',
        ticker: 'IPGP',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sivers Semiconductors',
        ticker: 'SIVE.ST',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Sweden',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Lightwave Logic',
        ticker: 'LWLG',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'nLIGHT',
        ticker: 'LASR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 2 ────────────────────────────────────────────────────────────────
  {
    name: 'Active Photonic Devices',
    color: '#22d3ee',
    glow: 'rgba(34,211,238,0.12)',
    dim: 'rgba(34,211,238,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers active components that generate, amplify, modulate, or detect light, including lasers, LEDs, and photodetectors.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Lumentum',
        ticker: 'LITE',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Coherent',
        ticker: 'COHR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'nLIGHT',
        ticker: 'LASR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sivers Semiconductors',
        ticker: 'SIVE.ST',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Sweden',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'IPG Photonics',
        ticker: 'IPGP',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'QD Laser',
        ticker: '6613.T',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sumitomo Electric',
        ticker: 'SMTOY',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Applied Optoelectronics',
        ticker: 'AAOI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Aeluma',
        ticker: 'ALMU',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'MACOM',
        ticker: 'MTSI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Semtech',
        ticker: 'SMTC',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Lightwave Logic',
        ticker: 'LWLG',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 3 ────────────────────────────────────────────────────────────────
  {
    name: 'Electro-Optical Connectivity IC',
    color: '#60a5fa',
    glow: 'rgba(96,165,250,0.12)',
    dim: 'rgba(96,165,250,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers ICs that bridge the electrical and optical domains, including drivers, TIAs, and DSPs for optical links.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'MACOM',
        ticker: 'MTSI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Semtech',
        ticker: 'SMTC',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Marvell',
        ticker: 'MRVL',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Credo Technology',
        ticker: 'CRDO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Astera Labs',
        ticker: 'ALAB',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Cisco',
        ticker: 'CSCO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'MaxLinear',
        ticker: 'MXL',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 4 ────────────────────────────────────────────────────────────────
  {
    name: 'PIC Platform & IP',
    color: '#a78bfa',
    glow: 'rgba(167,139,250,0.12)',
    dim: 'rgba(167,139,250,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers photonic integrated circuit platforms, IP blocks, and design ecosystems enabling PIC-based product development.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'POET Technologies',
        ticker: 'POET',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Canada',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Marvell',
        ticker: 'MRVL',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Credo Technology',
        ticker: 'CRDO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Astera Labs',
        ticker: 'ALAB',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Cisco',
        ticker: 'CSCO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Nokia',
        ticker: 'NOK',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Finland',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Quantum Computing Inc',
        ticker: 'QUBT',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Innolight',
        ticker: '300308.SZ',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'China',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Eoptolink',
        ticker: '300502.SZ',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'China',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Ayar Labs',
        ticker: null,
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Private',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Lightmatter',
        ticker: null,
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Private',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'HyperLight',
        ticker: null,
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Private',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 5 ────────────────────────────────────────────────────────────────
  {
    name: 'Foundry & Process Platform',
    color: '#818cf8',
    glow: 'rgba(129,140,248,0.12)',
    dim: 'rgba(129,140,248,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers photonic foundries and process platforms that manufacture PIC wafers for fabless customers.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Tower Semiconductor',
        ticker: 'TSEM',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Israel',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'GlobalFoundries',
        ticker: 'GFS',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'United Microelectronics (UMC)',
        ticker: 'UMC',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Taiwan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'TSMC',
        ticker: 'TSM',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Taiwan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Quantum Computing Inc',
        ticker: 'QUBT',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 6A ───────────────────────────────────────────────────────────────
  {
    label: 'L6A',
    name: 'Engine & Module',
    color: '#2dd4bf',
    glow: 'rgba(45,212,191,0.12)',
    dim: 'rgba(45,212,191,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers optical engines, co-packaged optics, and transceiver modules.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Coherent',
        ticker: 'COHR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Lumentum',
        ticker: 'LITE',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Applied Optoelectronics',
        ticker: 'AAOI',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Fabrinet',
        ticker: 'FN',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Innolight',
        ticker: '300308.SZ',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'China',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Eoptolink',
        ticker: '300502.SZ',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'China',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Ciena',
        ticker: 'CIEN',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sumitomo Electric',
        ticker: 'SMTOY',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Nokia',
        ticker: 'NOK',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Finland',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'POET Technologies',
        ticker: 'POET',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Canada',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Marvell',
        ticker: 'MRVL',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Credo Technology',
        ticker: 'CRDO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Cisco',
        ticker: 'CSCO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 6B ───────────────────────────────────────────────────────────────
  {
    label: 'L6B',
    name: 'Optical Infrastructure',
    color: '#38bdf8',
    glow: 'rgba(56,189,248,0.12)',
    dim: 'rgba(56,189,248,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers fiber, cabling, connectors, and passive optical infrastructure.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Corning',
        ticker: 'GLW',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Sumitomo Electric',
        ticker: 'SMTOY',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Prysmian',
        ticker: 'PRYMF',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Italy',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Amphenol',
        ticker: 'APH',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'TE Connectivity',
        ticker: 'TEL',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Switzerland',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Fujikura',
        ticker: 'FJTSY',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 6C ───────────────────────────────────────────────────────────────
  {
    label: 'L6C',
    name: 'Transport',
    color: '#fb923c',
    glow: 'rgba(251,146,60,0.12)',
    dim: 'rgba(251,146,60,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers optical transport systems, networking equipment, and WDM platforms.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Ciena',
        ticker: 'CIEN',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Nokia',
        ticker: 'NOK',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Finland',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Cisco',
        ticker: 'CSCO',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },

  // ── LAYER 7 ────────────────────────────────────────────────────────────────
  {
    label: 'L7',
    name: 'Test & Qualification',
    color: '#4ade80',
    glow: 'rgba(74,222,128,0.12)',
    dim: 'rgba(74,222,128,0.35)',
    overview: {
      description:
        'Placeholder description — to be written. This layer covers test equipment, measurement systems, and qualification services specific to photonic components and modules.',
      importance:
        'Placeholder importance — to be written.',
      tam: 'Placeholder — $XXB',
      growthDrivers: [
        'Placeholder growth driver 1 — to be written.',
        'Placeholder growth driver 2 — to be written.',
      ],
      keyTrends: [
        'Placeholder key trend 1 — to be written.',
        'Placeholder key trend 2 — to be written.',
      ],
    },
    companies: [
      {
        name: 'Keysight Technologies',
        ticker: 'KEYS',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Teradyne',
        ticker: 'TER',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Advantest',
        ticker: 'ATEYY',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Japan',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'FormFactor',
        ticker: 'FORM',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Aehr Test Systems',
        ticker: 'AEHR',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Viavi Solutions',
        ticker: 'VIAV',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
      {
        name: 'Cohu',
        ticker: 'COHU',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description: 'Placeholder — company description to be written.',
      },
    ],
  },
]

export const NEOCLOUD_LAYERS = [
  {
    name: 'AI Infrastructure & Neocloud Platforms',
    color: '#34d399',
    glow: 'rgba(52,211,153,0.12)',
    dim: 'rgba(52,211,153,0.35)',
    overview: {
      description:
        'Public neocloud platforms that build and operate accelerated computing infrastructure for artificial intelligence and high-performance computing workloads.',
      importance:
        'These companies sit between scarce power, data-center capacity, and advanced accelerators on one side and rapidly growing AI compute demand on the other.',
      tam: 'Expanding AI compute market',
      growthDrivers: [
        'Demand for large-scale training and inference capacity.',
        'Enterprise adoption of accelerated computing and specialized AI cloud platforms.',
      ],
      keyTrends: [
        'Rapid deployment of power-dense GPU infrastructure.',
        'Long-duration capacity commitments and rising capital intensity.',
      ],
    },
    companies: [
      {
        name: 'Nebius Group',
        ticker: 'NBIS',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Netherlands',
        type: 'Public',
        description:
          'AI infrastructure company providing a full-stack cloud platform for AI builders and enterprises.',
      },
      {
        name: 'CoreWeave',
        ticker: 'CRWV',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'USA',
        type: 'Public',
        description:
          'Specialized cloud platform providing accelerated computing infrastructure for AI workloads.',
      },
      {
        name: 'IREN',
        ticker: 'IREN',
        marketCap: null,
        revenueGrowth: null,
        grossMargin: null,
        country: 'Australia',
        type: 'Public',
        description:
          'Data-center operator developing power and computing infrastructure for AI cloud and other compute-intensive workloads.',
      },
    ],
  },
]

// AI infrastructure ecosystem data sourced from the supplied vertical list.
// Keep company additions here so every Market Map view shares one universe.
const aiInfrastructureCompany = (name, ticker, country) => ({
  name,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country,
  type: 'Public',
  description: 'Placeholder - company description to be written.',
})

const aiInfrastructureLayer = (name, color, companies) => ({
  name,
  color,
  glow: `${color}22`,
  dim: `${color}59`,
  overview: {
    description: 'Placeholder description - to be written.',
    importance: 'Placeholder importance - to be written.',
    tam: 'Placeholder - $XXB',
    growthDrivers: [
      'Placeholder growth driver 1 - to be written.',
      'Placeholder growth driver 2 - to be written.',
    ],
    keyTrends: [
      'Placeholder key trend 1 - to be written.',
      'Placeholder key trend 2 - to be written.',
    ],
  },
  companies,
})

export const AI_INFRASTRUCTURE_LAYERS = [
  aiInfrastructureLayer('GPU / ASIC', '#a3e635', [
    aiInfrastructureCompany('Nvidia', 'NVDA', 'USA'),
    aiInfrastructureCompany('Broadcom', 'AVGO', 'USA'),
    aiInfrastructureCompany('AMD', 'AMD', 'USA'),
    aiInfrastructureCompany('MediaTek', '2454.TW', 'Taiwan'),
    aiInfrastructureCompany('Marvell', 'MRVL', 'USA'),
  ]),
  aiInfrastructureLayer('CPU', '#fbbf24', [
    aiInfrastructureCompany('Intel', 'INTC', 'USA'),
  ]),
  aiInfrastructureLayer('Memory + Storage', '#f472b6', [
    aiInfrastructureCompany('SK Hynix', '000660.KS', 'South Korea'),
    aiInfrastructureCompany('Micron', 'MU', 'USA'),
    aiInfrastructureCompany('Samsung Electronics', '005930.KS', 'South Korea'),
  ]),
  aiInfrastructureLayer('Storage (ex. Memory)', '#fb923c', [
    aiInfrastructureCompany('SanDisk', 'SNDK', 'USA'),
    aiInfrastructureCompany('Kioxia', '285A.T', 'Japan'),
    aiInfrastructureCompany('Seagate', 'STX', 'USA'),
    aiInfrastructureCompany('Western Digital', 'WDC', 'USA'),
  ]),
  aiInfrastructureLayer('Server / Rack', '#38bdf8', [
    aiInfrastructureCompany('Quanta Computer', '2382.TW', 'Taiwan'),
    aiInfrastructureCompany('Wiwynn', '6669.TW', 'Taiwan'),
    aiInfrastructureCompany('Foxconn Industrial Internet', '601138.SS', 'China'),
    aiInfrastructureCompany('Inventec', '2356.TW', 'Taiwan'),
    aiInfrastructureCompany('Super Micro Computer', 'SMCI', 'USA'),
    aiInfrastructureCompany('Gigabyte Technology', '2376.TW', 'Taiwan'),
    aiInfrastructureCompany('Dell Technologies', 'DELL', 'USA'),
    aiInfrastructureCompany('Hewlett Packard Enterprise', 'HPE', 'USA'),
  ]),
  aiInfrastructureLayer('PCB / Substrate', '#c084fc', [
    aiInfrastructureCompany('Unimicron', '3037.TW', 'Taiwan'),
    aiInfrastructureCompany('Ibiden', '4062.T', 'Japan'),
  ]),
  aiInfrastructureLayer('Backplanes', '#2dd4bf', [
    aiInfrastructureCompany('Amphenol', 'APH', 'USA'),
  ]),
  aiInfrastructureLayer('Switches', '#60a5fa', [
    aiInfrastructureCompany('Arista Networks', 'ANET', 'USA'),
    aiInfrastructureCompany('Cisco', 'CSCO', 'USA'),
  ]),
  aiInfrastructureLayer('Transceivers', '#22d3ee', [
    aiInfrastructureCompany('Innolight', '300308.SZ', 'China'),
    aiInfrastructureCompany('Eoptolink', '300502.SZ', 'China'),
    aiInfrastructureCompany('Coherent', 'COHR', 'USA'),
  ]),
  aiInfrastructureLayer('Power / Thermal', '#ef4444', [
    aiInfrastructureCompany('Delta Electronics', '2308.TW', 'Taiwan'),
    aiInfrastructureCompany('Flex', 'FLEX', 'Singapore'),
    aiInfrastructureCompany('Eaton', 'ETN', 'Ireland'),
  ]),
  aiInfrastructureLayer('Mechanical & Electrical', '#94a3b8', [
    aiInfrastructureCompany('ABB', 'ABBN.SW', 'Switzerland'),
    aiInfrastructureCompany('Siemens', 'SIE.DE', 'Germany'),
    aiInfrastructureCompany('Legrand', 'LR.PA', 'France'),
    aiInfrastructureCompany('Caterpillar', 'CAT', 'USA'),
    aiInfrastructureCompany('Cummins', 'CMI', 'USA'),
    aiInfrastructureCompany('Quanta Services', 'PWR', 'USA'),
  ]),
  aiInfrastructureLayer('Foundry', '#818cf8', [
    aiInfrastructureCompany('TSMC', 'TSM', 'Taiwan'),
  ]),
]

// These are separate homepage grids, not layers inside one AI Infrastructure map.
export const AI_INFRASTRUCTURE_VERTICALS = [
  { id: 'gpu-asic', symbol: 'GPU', description: 'Accelerators, custom silicon, and the compute semiconductors behind AI workloads.', layer: AI_INFRASTRUCTURE_LAYERS[0] },
  { id: 'cpu', symbol: 'CPU', description: 'General-purpose processors that coordinate servers and AI systems.', layer: AI_INFRASTRUCTURE_LAYERS[1] },
  { id: 'memory-storage', symbol: 'MEM', description: 'DRAM, HBM, NAND, and memory suppliers critical to AI system capacity.', layer: AI_INFRASTRUCTURE_LAYERS[2] },
  { id: 'storage', symbol: 'SSD', description: 'Persistent storage suppliers outside the core memory stack.', layer: AI_INFRASTRUCTURE_LAYERS[3] },
  { id: 'server-rack', symbol: 'RACK', description: 'Server, rack, and manufacturing partners that assemble AI data-center systems.', layer: AI_INFRASTRUCTURE_LAYERS[4] },
  { id: 'pcb-substrate', symbol: 'PCB', description: 'High-density circuit boards and substrates connecting advanced compute systems.', layer: AI_INFRASTRUCTURE_LAYERS[5] },
  { id: 'backplanes', symbol: 'I/O', description: 'Backplane and interconnect providers that move signals through dense systems.', layer: AI_INFRASTRUCTURE_LAYERS[6] },
  { id: 'switches', symbol: 'NET', description: 'Ethernet switching systems supporting AI clusters and data-center fabrics.', layer: AI_INFRASTRUCTURE_LAYERS[7] },
  { id: 'transceivers', symbol: 'OPT', description: 'Optical transceivers that connect high-bandwidth AI clusters.', layer: AI_INFRASTRUCTURE_LAYERS[8] },
  { id: 'power-thermal', symbol: 'PWR', description: 'Power conversion, distribution, cooling, and thermal management for AI facilities.', layer: AI_INFRASTRUCTURE_LAYERS[9] },
  { id: 'mechanical-electrical', symbol: 'M/E', description: 'Electrical and industrial equipment needed to build and operate AI infrastructure.', layer: AI_INFRASTRUCTURE_LAYERS[10] },
  { id: 'foundry', symbol: 'FAB', description: 'Leading-edge silicon manufacturing capacity for advanced compute chips.', layer: AI_INFRASTRUCTURE_LAYERS[11] },
]

const etfCompany = (ticker) => ({
  name: `${ticker} ETF`,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country: 'USA',
  type: 'Public',
  description: 'ETF benchmark - description to be written.',
})

export const ETF_LAYERS = [
  {
    name: 'ETF Benchmarks',
    color: '#34d399',
    glow: '#34d39922',
    dim: '#34d39959',
    overview: {
      description: 'ETF benchmarks for software, broad market, semiconductors, memory, and AI themes.',
      importance: 'A compact reference set for tracking broad market and technology-theme performance.',
      tam: 'Not applicable - ETF reference set.',
      growthDrivers: ['Benchmark and sector allocation demand.'],
      keyTrends: ['Technology, semiconductor, memory, and AI-theme performance.'],
    },
    companies: ['IGV', 'QQQ', 'SOXX', 'SPY', 'DRAM', 'AIS'].map(etfCompany),
  },
]

const btmEnergyCompany = (ticker) => ({
  name: ticker,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country: 'USA',
  type: 'Public',
  description: 'BTM Energy company - description to be written.',
})

export const BTM_ENERGY_LAYERS = [
  {
    name: 'Behind-the-Meter Energy',
    color: '#f59e0b',
    glow: '#f59e0b22',
    dim: '#f59e0b59',
    overview: {
      description: 'Distributed energy, generation, and fuel-cell companies in the selected BTM Energy reference set.',
      importance: 'A focused group for monitoring power availability and behind-the-meter energy infrastructure.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: ['BE', 'GEV', 'FCEL', 'CGEH'].map(btmEnergyCompany),
  },
]

const hyperscalerCompany = (name, ticker) => ({
  name,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country: 'USA',
  type: 'Public',
  description: 'Hyperscaler company - description to be written.',
})

export const HYPERSCALER_LAYERS = [
  {
    name: 'Hyperscalers',
    color: '#38bdf8',
    glow: '#38bdf822',
    dim: '#38bdf859',
    overview: {
      description: 'Large-scale cloud and AI infrastructure operators in the selected hyperscaler reference set.',
      importance: 'A focused group for monitoring the cloud platforms that fund and deploy global AI infrastructure.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: [
      hyperscalerCompany('Google', 'GOOGL'),
      hyperscalerCompany('Amazon', 'AMZN'),
      hyperscalerCompany('Meta', 'META'),
      hyperscalerCompany('Microsoft', 'MSFT'),
    ],
  },
]

const semiconductorProcessControlCompany = (name, ticker, country) => ({
  name,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country,
  type: 'Public',
  description: 'Semiconductor process control company - description to be written.',
})

export const SEMICONDUCTOR_PROCESS_CONTROL_LAYERS = [
  {
    name: 'Semiconductor Process Control',
    color: '#a78bfa',
    glow: '#a78bfa22',
    dim: '#a78bfa59',
    overview: {
      description: 'Metrology, inspection, analytical instrumentation, and wafer-process equipment providers in the selected reference set.',
      importance: 'A focused group for monitoring the process-control tools that support semiconductor yield, reliability, and advanced-node production.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: [
      semiconductorProcessControlCompany('Rigaku', '268A.T', 'Japan'),
      semiconductorProcessControlCompany('KLA', 'KLAC', 'USA'),
      semiconductorProcessControlCompany('Onto Innovation', 'ONTO', 'USA'),
      semiconductorProcessControlCompany('Camtek', 'CAMT', 'Israel'),
      semiconductorProcessControlCompany('Bruker', 'BRKR', 'USA'),
      semiconductorProcessControlCompany('Thermo Fisher', 'TMO', 'USA'),
      semiconductorProcessControlCompany('Lam Research', 'LRCX', 'USA'),
      semiconductorProcessControlCompany('Applied Materials', 'AMAT', 'USA'),
    ],
  },
]

const softwareCompany = (name, ticker, country = 'USA', type = 'Public', description = 'Software company - description to be written.') => ({
  name,
  ticker,
  marketCap: null,
  revenueGrowth: null,
  grossMargin: null,
  country,
  type,
  description,
})

// Separate software grids: each category has its own market-map page rather
// than being combined into a single generic software layer.
export const DATA_MANAGEMENT_LAYERS = [
  {
    name: 'Data Management',
    color: '#0ea5e9',
    glow: '#0ea5e922',
    dim: '#0ea5e959',
    overview: {
      description: 'Data platforms, databases, integration tools, and streaming infrastructure used to manage enterprise data.',
      importance: 'A focused software reference set for tracking the data layer behind analytics and AI applications.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: [
      softwareCompany('Snowflake', 'SNOW'),
      softwareCompany('Couchbase', null, 'USA', 'Private', 'Formerly BASE; acquired by Haveli Investments in 2025.'),
      softwareCompany('Elastic', 'ESTC'),
      softwareCompany('MongoDB', 'MDB'),
      softwareCompany('Informatica', null, 'USA', 'Private', 'Formerly INFA; acquired by Salesforce in 2025.'),
      softwareCompany('Confluent', null, 'USA', 'Private', 'Formerly CFLT; acquired by IBM in 2026.'),
    ],
  },
]

export const DEVOPS_LAYERS = [
  {
    name: 'DevOps',
    color: '#8b5cf6',
    glow: '#8b5cf622',
    dim: '#8b5cf659',
    overview: {
      description: 'Cloud infrastructure, observability, application delivery, collaboration, and IT operations software.',
      importance: 'A focused software reference set for tracking tools used to build, deploy, secure, and operate modern applications.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: [
      softwareCompany('Akamai Technologies', 'AKAM'),
      softwareCompany('Atlassian', 'TEAM'),
      softwareCompany('Datadog', 'DDOG'),
      softwareCompany('DigitalOcean', 'DOCN'),
      softwareCompany('Fastly', 'FSLY'),
      softwareCompany('GitLab', 'GTLB'),
      softwareCompany('JFrog', 'FROG'),
      softwareCompany('NetApp', 'NTAP'),
      softwareCompany('NetScout Systems', 'NTCT'),
      softwareCompany('PagerDuty', 'PD'),
      softwareCompany('SolarWinds', null, 'USA', 'Private', 'Formerly SWI; acquired by Turn/River Capital in 2025.'),
      softwareCompany('Twilio', 'TWLO'),
      softwareCompany('Appian', 'APPN'),
      softwareCompany('Dynatrace', 'DT'),
      softwareCompany('VMware', null, 'USA', 'Private', 'Formerly VMW; acquired by Broadcom in 2023.'),
      softwareCompany('Everbridge', null, 'USA', 'Private', 'Formerly EVBG; acquired by Thoma Bravo in 2024.'),
    ],
  },
]

export const BI_ANALYTICS_LAYERS = [
  {
    name: 'BI & Analytics',
    color: '#ec4899',
    glow: '#ec489922',
    dim: '#ec489959',
    overview: {
      description: 'Business intelligence, analytics, data activation, and AI application software providers.',
      importance: 'A focused software reference set for monitoring the analytical tools that turn enterprise data into decisions and workflows.',
      tam: 'Placeholder - to be written.',
      growthDrivers: ['Placeholder growth driver - to be written.'],
      keyTrends: ['Placeholder key trend - to be written.'],
    },
    companies: [
      softwareCompany('Palantir Technologies', 'PLTR'),
      softwareCompany('Teradata', 'TDC'),
      softwareCompany('Elastic', 'ESTC'),
      softwareCompany('Domo', 'DOMO'),
      softwareCompany('Amplitude', 'AMPL'),
      softwareCompany('LiveRamp', 'RAMP'),
      softwareCompany('Karooooo', 'KARO', 'Singapore'),
      softwareCompany('Strategy', 'MSTR'),
      softwareCompany('Tuya', 'TUYA', 'China'),
      softwareCompany('UiPath', 'PATH'),
      softwareCompany('Fair Isaac', 'FICO'),
      softwareCompany('C3.ai', 'AI'),
    ],
  },
]

export const SOFTWARE_VERTICALS = [
  { id: 'data-management', symbol: 'DATA', description: 'Databases, data platforms, integration, and streaming infrastructure.', layer: DATA_MANAGEMENT_LAYERS[0] },
  { id: 'devops', symbol: 'DEV', description: 'Application delivery, observability, cloud infrastructure, and IT operations software.', layer: DEVOPS_LAYERS[0] },
  { id: 'bi-analytics', symbol: 'BI', description: 'Business intelligence, analytics, data activation, and AI application software.', layer: BI_ANALYTICS_LAYERS[0] },
]

export const MARKET_MAPS = {
  optics: {
    id: 'optics',
    name: 'Optics',
    contextTheme: 'photonics',
    symbol: '◉',
    description:
      'Photonic components, PICs, transceivers, and optical interconnects enabling next-gen connectivity.',
    marketCap: '$180B',
    mapTitle: 'Optics Ecosystem Map',
    stackLabel: 'Optical Investing Stack',
    stackTitle: 'Dissecting the full structure of optical infrastructure',
    stackDescription:
      'Click any deck to open that layer, compare public names, and drill into company-level data.',
    sideDescription:
      'companies mapped from substrates through test and qualification.',
    footer:
      'Optics · Photonic Integrated Circuits & Optical Interconnects',
    layers: OPTICS_LAYERS,
  },
  neoclouds: {
    id: 'neoclouds',
    name: 'Neoclouds',
    contextTheme: 'neoclouds',
    symbol: 'N',
    description:
      'Specialized AI cloud platforms combining accelerated compute, data-center capacity, power, and software.',
    marketCap: 'Live',
    mapTitle: 'Neoclouds Ecosystem Map',
    stackLabel: 'AI Compute Investing Stack',
    stackTitle: 'Mapping the public neocloud infrastructure platform',
    stackDescription:
      'Open the layer to compare public neoclouds, analyze their stocks, and drill into company-level data.',
    sideDescription:
      'public neocloud platforms mapped across accelerated AI infrastructure.',
    footer:
      'Neoclouds · Accelerated Compute & AI Infrastructure',
    layers: NEOCLOUD_LAYERS,
  },
  etfs: {
    id: 'etfs',
    name: 'ETFs',
    contextTheme: 'etfs',
    symbol: 'ETF',
    description: 'A focused ETF reference set spanning software, broad market, semiconductors, memory, and AI themes.',
    marketCap: 'Live',
    mapTitle: 'ETF Market Map',
    stackLabel: 'Market Reference Set',
    stackTitle: 'Technology and market ETF benchmarks',
    stackDescription: 'Open the ETF deck to compare the selected benchmark instruments and their live market data.',
    sideDescription: 'ETF benchmarks in the selected market-reference set.',
    footer: 'ETFs - Market & Technology Benchmarks',
    layers: ETF_LAYERS,
  },
  'btm-energy': {
    id: 'btm-energy',
    name: 'BTM Energy',
    contextTheme: 'btm-energy',
    symbol: 'BTM',
    description: 'A focused set of behind-the-meter energy, generation, and fuel-cell companies.',
    marketCap: 'Live',
    mapTitle: 'BTM Energy Market Map',
    stackLabel: 'Distributed Energy Investing Set',
    stackTitle: 'Behind-the-meter energy and power infrastructure',
    stackDescription: 'Open the BTM Energy deck to compare the selected companies and their live market data.',
    sideDescription: 'public companies in the selected BTM Energy reference set.',
    footer: 'BTM Energy - Distributed Power & Fuel Cells',
    layers: BTM_ENERGY_LAYERS,
  },
  hyperscalers: {
    id: 'hyperscalers',
    name: 'Hyperscalers',
    contextTheme: 'hyperscalers',
    symbol: 'HYP',
    description: 'Cloud, advertising, commerce, and software platforms operating global-scale AI infrastructure.',
    marketCap: 'Live',
    mapTitle: 'Hyperscalers Market Map',
    stackLabel: 'Global AI Platform Set',
    stackTitle: 'Cloud and AI infrastructure hyperscalers',
    stackDescription: 'Open the Hyperscalers deck to compare the selected companies and their live market data.',
    sideDescription: 'public hyperscalers in the selected AI platform reference set.',
    footer: 'Hyperscalers - Cloud, AI & Digital Platforms',
    layers: HYPERSCALER_LAYERS,
  },
  'semiconductor-process-control': {
    id: 'semiconductor-process-control',
    name: 'Semiconductor Process Control',
    contextTheme: 'semiconductor-process-control',
    symbol: 'SPC',
    description: 'Metrology, inspection, analytical instrumentation, and wafer-process equipment for semiconductor manufacturing.',
    marketCap: 'Live',
    mapTitle: 'Semiconductor Process Control Map',
    stackLabel: 'Semiconductor Equipment Reference Set',
    stackTitle: 'Process control, metrology, and wafer equipment',
    stackDescription: 'Open the Semiconductor Process Control deck to compare the selected companies and their live market data.',
    sideDescription: 'public companies in the selected semiconductor process-control reference set.',
    footer: 'Semiconductor Process Control - Metrology, Inspection & Equipment',
    layers: SEMICONDUCTOR_PROCESS_CONTROL_LAYERS,
  },
  ...Object.fromEntries(SOFTWARE_VERTICALS.map((vertical) => [
    vertical.id,
    {
      id: vertical.id,
      name: vertical.layer.name,
      contextTheme: 'software',
      symbol: vertical.symbol,
      description: vertical.description,
      marketCap: 'Live',
      mapTitle: `${vertical.layer.name} Market Map`,
      stackLabel: 'Software Reference Set',
      stackTitle: vertical.layer.name,
      stackDescription: vertical.description,
      sideDescription: 'public and former-public companies mapped in this software category.',
      footer: `Software - ${vertical.layer.name}`,
      layers: [vertical.layer],
    },
  ])),
  ...Object.fromEntries(AI_INFRASTRUCTURE_VERTICALS.map((vertical) => [
    vertical.id,
    {
      id: vertical.id,
      name: vertical.layer.name,
      contextTheme: 'ai-infrastructure',
      symbol: vertical.symbol,
      description: vertical.description,
      marketCap: 'Live',
      mapTitle: `${vertical.layer.name} Market Map`,
      stackLabel: 'AI Infrastructure Vertical',
      stackTitle: vertical.layer.name,
      stackDescription: vertical.description,
      sideDescription: 'public companies mapped in this AI infrastructure vertical.',
      footer: `AI Infrastructure - ${vertical.layer.name}`,
      layers: [vertical.layer],
    },
  ])),
}
